### Завдання 1: Створення матриць та векторів
1. Створіть `numpy` вектор `vector` розмірністю 10 з випадковими дійсними значеннями в діапазоні від 0 до 1. Можна скористатись двома альтернативними варіантами:
  1. Генерація випадкових чисел з модулем [`random.uniform`](https://docs.python.org/3/library/random.html).
  2. Створення вектора з допомогою метода `numpy` [np.random.rand](https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html)

2. Створіть матрицю `matrix` типу `numpy.array` розмірності 3x3 з наступними значеннями

  $$
  matrix = \begin{bmatrix}
  11 & 14 & 17 \\
  20 & 23 & 26 \\
  29 & 32 & 35
  \end{bmatrix}
  $$

  будь-яким відомими Вам способом.

Виведіть на екран вектор і матрицю, а також їх розміри.


In [1]:
import numpy as np

vector = np.random.rand(10)

matrix = np.array([
    [11, 14, 17],
    [20, 23, 26],
    [29, 32, 35]
])

print("Вектор:")
print(vector)
print("Розмір вектора:", vector.shape)

print("\nМатриця:")
print(matrix)
print("Розмір матриці:", matrix.shape)

Вектор:
[0.54027315 0.20337691 0.24014356 0.33121951 0.83899452 0.27644366
 0.86441691 0.34441098 0.32179488 0.10651351]
Розмір вектора: (10,)

Матриця:
[[11 14 17]
 [20 23 26]
 [29 32 35]]
Розмір матриці: (3, 3)



### Завдання 2: Операції над векторами та матрицями
Виконайте кожну з зазначених операцій над зазначеними оʼєктами і виведіть результат на екран:
1. Додайте до кожного значення вектора `vector` число 10 і округліть кожне значення до 2 знаків після коми без використання циклів.
2. Помножте кожен елемент матриці з першого завдання на 2 без використання циклів.
3. Створіть новий вектор, який містить квадрат кожного `vector` без циклів.


In [2]:
vector_plus_10 = np.round(vector + 10, 2)
print("Вектор + 10:")
print(vector_plus_10)

matrix_times_2 = matrix * 2
print("\nМатриця помножена на 2:")
print(matrix_times_2)

vector_squared = np.square(vector)
print("\nКвадрат елементів вектора:")
print(vector_squared)

Вектор + 10:
[10.54 10.2  10.24 10.33 10.84 10.28 10.86 10.34 10.32 10.11]

Матриця помножена на 2:
[[22 28 34]
 [40 46 52]
 [58 64 70]]

Квадрат елементів вектора:
[0.29189507 0.04136217 0.05766893 0.10970637 0.7039118  0.0764211
 0.7472166  0.11861892 0.10355195 0.01134513]



### Завдання 3: Множення матриць
1. Задані дві матриці `A` і `B`розмірностями 3x2 та 2х3. Виконайте їхнє множення, щоб отримати матрицю 2x2. Виведіть результуючу матрицю `result_matrix` на екран.

2. Заданий вектор `C` розмірністю 2х1. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на вектор `C` і який результат буде. А потім виконайте множення і виведіть результат на екран.

3. Задана матриця `D` розмірністю 2х2. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на матрицю `D` і який результат буде. А потім виконайте множення і виведіть результат на екран.

In [3]:
A = np.array(
    [[0.18, 0.53],
     [0.75, 0.47],
     [0.35, 0.21]])

B = np.array(
    [[0.17, 0.58, 0.75],
     [0.38, 0.11, 0.15]])

C = np.array([[0], [1]])

D = np.array([[0,1], [1,0]])

display(A, B, C, D)

array([[0.18, 0.53],
       [0.75, 0.47],
       [0.35, 0.21]])

array([[0.17, 0.58, 0.75],
       [0.38, 0.11, 0.15]])

array([[0],
       [1]])

array([[0, 1],
       [1, 0]])

In [4]:
result_matrix = np.dot(B, A)
result_matrix

array([[0.7281, 0.5202],
       [0.2034, 0.2846]])

In [5]:
result_C = np.dot(result_matrix, C)
print("\nresult_C (2x1):\n", result_C)


result_C (2x1):
 [[0.5202]
 [0.2846]]


In [6]:
result_D = np.dot(result_matrix, D)
print("\nresult_D (2x2):\n", result_D)


result_D (2x2):
 [[0.5202 0.7281]
 [0.2846 0.2034]]



### Завдання 4: Транспонування матриць
1. Транспонуйте `result_matrix`.
2. Зробіть транспонування вектора `vector` і виведіть форму нової структури. Чи бачите ви зміну?
3. Використайте операцію `numpy.expand_dims` над вектором `vector` з аргументом axis=1. Запишіть отриманий результат в змінну `column_vector` і виведіть на екран. Порівняйте з `vector`.
4. Зробіть транспонування `column_vector`, виведіть результат на екран разом з розмірностями отриманої структури.




In [7]:
result_matrix_T = result_matrix.T
print("Транспонована result_matrix:\n", result_matrix_T)

Транспонована result_matrix:
 [[0.7281 0.2034]
 [0.5202 0.2846]]


In [8]:
vector_T = vector.T
print("\nПісля звичайного транспонування vector:\n", vector_T)
print("Розмір:", vector_T.shape)


Після звичайного транспонування vector:
 [0.54027315 0.20337691 0.24014356 0.33121951 0.83899452 0.27644366
 0.86441691 0.34441098 0.32179488 0.10651351]
Розмір: (10,)


Для звичайного вектора vector (1D) транспонування нічого не змінює.

In [9]:
column_vector = np.expand_dims(vector, axis=1)
print("\nСтовпчиковий вектор column_vector:\n", column_vector)
print("Розмір:", column_vector.shape)


Стовпчиковий вектор column_vector:
 [[0.54027315]
 [0.20337691]
 [0.24014356]
 [0.33121951]
 [0.83899452]
 [0.27644366]
 [0.86441691]
 [0.34441098]
 [0.32179488]
 [0.10651351]]
Розмір: (10, 1)


vector — це одномірний масив, тобто просто 10 чисел у лінію. Після застосування expand_dims з axis=1 ми отримали двовимірний масив, тобто стовпчик, де кожен елемент розташований у окремому рядку.

In [10]:
column_vector_T = column_vector.T
print("\nТранспонований column_vector:\n", column_vector_T)
print("Розмір:", column_vector_T.shape)


Транспонований column_vector:
 [[0.54027315 0.20337691 0.24014356 0.33121951 0.83899452 0.27644366
  0.86441691 0.34441098 0.32179488 0.10651351]]
Розмір: (1, 10)


Таким чином, транспонування у 2D дійсно змінює орієнтацію вектора.